name: Deploy with Key Vault Variables
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Install Azure CLI
      uses: azure/setup-azcli@v1
    - name: Set Variables from Key Vault
      run: |
        echo "TF_VAR_rgname=$(az keyvault secret show --name rgname --vault-name trung-demo-oppgave7 --query value -o tsv)" >> $GITHUB_ENV
        echo "TF_VAR_location=$(az keyvault secret show --name location --vault-name trung-demo-oppgave7 --query value -o tsv)" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    - name: Initialize Terraform
      run: terraform init
    - name: Apply Terraform
      run: terraform apply -auto-approve
